CREATE USER usuario WITH PASSWORD 'user';
GRANT CONNECT ON DATABASE sisinf_grupo_c05 TO usuario;
GRANT USAGE ON SCHEMA public TO usuario;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO usuario;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO usuario;
GRANT INSERT ON Entrada, Cliente, Ent_But, Prod_Ent, Comentario TO usuario;
GRANT UPDATE ON Cliente TO usuario;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT UPDATE ON Cliente TO usuario;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT INSERT ON Entrada, Cliente, Ent_But, Prod_Ent, Comentario TO usuario;

CREATE USER admin WITH PASSWORD 'admin';
GRANT CONNECT ON DATABASE sisinf_grupo_c05 TO admin;
GRANT USAGE ON SCHEMA public TO admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO admin;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO admin